/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedVideoaulasRouteImport } from './routes/_authenticated/videoaulas'
import { Route as AuthenticatedFlashcardsRouteImport } from './routes/_authenticated/flashcards'
import { Route as AuthenticatedDebateRouteImport } from './routes/_authenticated/debate'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBibliotecaRouteImport } from './routes/_authenticated/biblioteca'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedTutorIndexRouteImport } from './routes/_authenticated/tutor.index'
import { Route as AuthenticatedMapasIndexRouteImport } from './routes/_authenticated/mapas.index'
import { Route as AuthenticatedEscritaIndexRouteImport } from './routes/_authenticated/escrita.index'
import { Route as AuthenticatedTutorThreadIdRouteImport } from './routes/_authenticated/tutor.$threadId'
import { Route as AuthenticatedMapasMapIdRouteImport } from './routes/_authenticated/mapas.$mapId'
import { Route as AuthenticatedEscritaEssayIdRouteImport } from './routes/_authenticated/escrita.$essayId'
import { Route as AuthenticatedBibliotecaLerIdRouteImport } from './routes/_authenticated/biblioteca.ler.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVideoaulasRoute = AuthenticatedVideoaulasRouteImport.update({
  id: '/videoaulas',
  path: '/videoaulas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFlashcardsRoute = AuthenticatedFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDebateRoute = AuthenticatedDebateRouteImport.update({
  id: '/debate',
  path: '/debate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBibliotecaRoute = AuthenticatedBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTutorIndexRoute = AuthenticatedTutorIndexRouteImport.update({
  id: '/tutor/',
  path: '/tutor/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapasIndexRoute = AuthenticatedMapasIndexRouteImport.update({
  id: '/mapas/',
  path: '/mapas/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEscritaIndexRoute =
  AuthenticatedEscritaIndexRouteImport.update({
    id: '/escrita/',
    path: '/escrita/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTutorThreadIdRoute =
  AuthenticatedTutorThreadIdRouteImport.update({
    id: '/tutor/$threadId',
    path: '/tutor/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMapasMapIdRoute = AuthenticatedMapasMapIdRouteImport.update({
  id: '/mapas/$mapId',
  path: '/mapas/$mapId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEscritaEssayIdRoute =
  AuthenticatedEscritaEssayIdRouteImport.update({
    id: '/escrita/$essayId',
    path: '/escrita/$essayId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBibliotecaLerIdRoute =
  AuthenticatedBibliotecaLerIdRouteImport.update({
    id: '/ler/$id',
    path: '/ler/$id',
    getParentRoute: () => AuthenticatedBibliotecaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/debate': typeof AuthenticatedDebateRoute
  '/flashcards': typeof AuthenticatedFlashcardsRoute
  '/videoaulas': typeof AuthenticatedVideoaulasRoute
  '/api/chat': typeof ApiChatRoute
  '/escrita/$essayId': typeof AuthenticatedEscritaEssayIdRoute
  '/mapas/$mapId': typeof AuthenticatedMapasMapIdRoute
  '/tutor/$threadId': typeof AuthenticatedTutorThreadIdRoute
  '/escrita/': typeof AuthenticatedEscritaIndexRoute
  '/mapas/': typeof AuthenticatedMapasIndexRoute
  '/tutor/': typeof AuthenticatedTutorIndexRoute
  '/biblioteca/ler/$id': typeof AuthenticatedBibliotecaLerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/debate': typeof AuthenticatedDebateRoute
  '/flashcards': typeof AuthenticatedFlashcardsRoute
  '/videoaulas': typeof AuthenticatedVideoaulasRoute
  '/api/chat': typeof ApiChatRoute
  '/escrita/$essayId': typeof AuthenticatedEscritaEssayIdRoute
  '/mapas/$mapId': typeof AuthenticatedMapasMapIdRoute
  '/tutor/$threadId': typeof AuthenticatedTutorThreadIdRoute
  '/escrita': typeof AuthenticatedEscritaIndexRoute
  '/mapas': typeof AuthenticatedMapasIndexRoute
  '/tutor': typeof AuthenticatedTutorIndexRoute
  '/biblioteca/ler/$id': typeof AuthenticatedBibliotecaLerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/biblioteca': typeof AuthenticatedBibliotecaRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/debate': typeof AuthenticatedDebateRoute
  '/_authenticated/flashcards': typeof AuthenticatedFlashcardsRoute
  '/_authenticated/videoaulas': typeof AuthenticatedVideoaulasRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/escrita/$essayId': typeof AuthenticatedEscritaEssayIdRoute
  '/_authenticated/mapas/$mapId': typeof AuthenticatedMapasMapIdRoute
  '/_authenticated/tutor/$threadId': typeof AuthenticatedTutorThreadIdRoute
  '/_authenticated/escrita/': typeof AuthenticatedEscritaIndexRoute
  '/_authenticated/mapas/': typeof AuthenticatedMapasIndexRoute
  '/_authenticated/tutor/': typeof AuthenticatedTutorIndexRoute
  '/_authenticated/biblioteca/ler/$id': typeof AuthenticatedBibliotecaLerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/agenda'
    | '/biblioteca'
    | '/dashboard'
    | '/debate'
    | '/flashcards'
    | '/videoaulas'
    | '/api/chat'
    | '/escrita/$essayId'
    | '/mapas/$mapId'
    | '/tutor/$threadId'
    | '/escrita/'
    | '/mapas/'
    | '/tutor/'
    | '/biblioteca/ler/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/agenda'
    | '/biblioteca'
    | '/dashboard'
    | '/debate'
    | '/flashcards'
    | '/videoaulas'
    | '/api/chat'
    | '/escrita/$essayId'
    | '/mapas/$mapId'
    | '/tutor/$threadId'
    | '/escrita'
    | '/mapas'
    | '/tutor'
    | '/biblioteca/ler/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cadastro'
    | '/login'
    | '/_authenticated/agenda'
    | '/_authenticated/biblioteca'
    | '/_authenticated/dashboard'
    | '/_authenticated/debate'
    | '/_authenticated/flashcards'
    | '/_authenticated/videoaulas'
    | '/api/chat'
    | '/_authenticated/escrita/$essayId'
    | '/_authenticated/mapas/$mapId'
    | '/_authenticated/tutor/$threadId'
    | '/_authenticated/escrita/'
    | '/_authenticated/mapas/'
    | '/_authenticated/tutor/'
    | '/_authenticated/biblioteca/ler/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/videoaulas': {
      id: '/_authenticated/videoaulas'
      path: '/videoaulas'
      fullPath: '/videoaulas'
      preLoaderRoute: typeof AuthenticatedVideoaulasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flashcards': {
      id: '/_authenticated/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof AuthenticatedFlashcardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/debate': {
      id: '/_authenticated/debate'
      path: '/debate'
      fullPath: '/debate'
      preLoaderRoute: typeof AuthenticatedDebateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblioteca': {
      id: '/_authenticated/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AuthenticatedBibliotecaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tutor/': {
      id: '/_authenticated/tutor/'
      path: '/tutor'
      fullPath: '/tutor/'
      preLoaderRoute: typeof AuthenticatedTutorIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mapas/': {
      id: '/_authenticated/mapas/'
      path: '/mapas'
      fullPath: '/mapas/'
      preLoaderRoute: typeof AuthenticatedMapasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escrita/': {
      id: '/_authenticated/escrita/'
      path: '/escrita'
      fullPath: '/escrita/'
      preLoaderRoute: typeof AuthenticatedEscritaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tutor/$threadId': {
      id: '/_authenticated/tutor/$threadId'
      path: '/tutor/$threadId'
      fullPath: '/tutor/$threadId'
      preLoaderRoute: typeof AuthenticatedTutorThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mapas/$mapId': {
      id: '/_authenticated/mapas/$mapId'
      path: '/mapas/$mapId'
      fullPath: '/mapas/$mapId'
      preLoaderRoute: typeof AuthenticatedMapasMapIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escrita/$essayId': {
      id: '/_authenticated/escrita/$essayId'
      path: '/escrita/$essayId'
      fullPath: '/escrita/$essayId'
      preLoaderRoute: typeof AuthenticatedEscritaEssayIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblioteca/ler/$id': {
      id: '/_authenticated/biblioteca/ler/$id'
      path: '/ler/$id'
      fullPath: '/biblioteca/ler/$id'
      preLoaderRoute: typeof AuthenticatedBibliotecaLerIdRouteImport
      parentRoute: typeof AuthenticatedBibliotecaRoute
    }
  }
}

interface AuthenticatedBibliotecaRouteChildren {
  AuthenticatedBibliotecaLerIdRoute: typeof AuthenticatedBibliotecaLerIdRoute
}

const AuthenticatedBibliotecaRouteChildren: AuthenticatedBibliotecaRouteChildren =
  {
    AuthenticatedBibliotecaLerIdRoute: AuthenticatedBibliotecaLerIdRoute,
  }

const AuthenticatedBibliotecaRouteWithChildren =
  AuthenticatedBibliotecaRoute._addFileChildren(
    AuthenticatedBibliotecaRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedBibliotecaRoute: typeof AuthenticatedBibliotecaRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDebateRoute: typeof AuthenticatedDebateRoute
  AuthenticatedFlashcardsRoute: typeof AuthenticatedFlashcardsRoute
  AuthenticatedVideoaulasRoute: typeof AuthenticatedVideoaulasRoute
  AuthenticatedEscritaEssayIdRoute: typeof AuthenticatedEscritaEssayIdRoute
  AuthenticatedMapasMapIdRoute: typeof AuthenticatedMapasMapIdRoute
  AuthenticatedTutorThreadIdRoute: typeof AuthenticatedTutorThreadIdRoute
  AuthenticatedEscritaIndexRoute: typeof AuthenticatedEscritaIndexRoute
  AuthenticatedMapasIndexRoute: typeof AuthenticatedMapasIndexRoute
  AuthenticatedTutorIndexRoute: typeof AuthenticatedTutorIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedBibliotecaRoute: AuthenticatedBibliotecaRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDebateRoute: AuthenticatedDebateRoute,
  AuthenticatedFlashcardsRoute: AuthenticatedFlashcardsRoute,
  AuthenticatedVideoaulasRoute: AuthenticatedVideoaulasRoute,
  AuthenticatedEscritaEssayIdRoute: AuthenticatedEscritaEssayIdRoute,
  AuthenticatedMapasMapIdRoute: AuthenticatedMapasMapIdRoute,
  AuthenticatedTutorThreadIdRoute: AuthenticatedTutorThreadIdRoute,
  AuthenticatedEscritaIndexRoute: AuthenticatedEscritaIndexRoute,
  AuthenticatedMapasIndexRoute: AuthenticatedMapasIndexRoute,
  AuthenticatedTutorIndexRoute: AuthenticatedTutorIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
